author: jrydberg
kind: gilliam#release
message: null
name: '2'
services:
  _store:
    command: null
    env: {}
    image: gilliam/etcd
    ports:
    - 4001
    - 7001
  api:
    command: bin/api
    env: {}
    image: gilliam/router:8efbfc70
    ports:
    - 80
  router:
    command: bin/router
    env: {}
    image: gilliam/router:8efbfc70
    ports:
    - 80
