author: jrydberg
kind: gilliam#release
message: null
name: '2'
services:
  _bootstrap:
    command: bin/bootstrap
    env: {}
    image: gilliam/scheduler-_bootstrap:75d28b29c4caa7480c53f189700860fa
    options: {}
    ports: []
  _store:
    command: null
    env: {}
    image: gilliam/etcd
    options: {}
    ports:
    - 4001
    - 7001
  _worker:
    command: bin/worker
    env: {}
    image: gilliam/scheduler-_worker:75d28b29c4caa7480c53f189700860fa
    options: {}
    ports: []
  api:
    command: bin/api
    env: {}
    image: gilliam/scheduler-api:75d28b29c4caa7480c53f189700860fa
    options: {}
    ports:
    - 80
