author: jrydberg
kind: gilliam#release
message: null
name: '2'
services:
  _bootstrap:
    command: bin/bootstrap
    env: {}
    image: gilliam/scheduler:f3f3bfb5
    ports: []
  _cache:
    command: null
    env: {}
    image: gilliam/redis
    ports:
    - 6379
  _store:
    command: null
    env: {}
    image: gilliam/etcd
    ports:
    - 4001
    - 7001
  _worker:
    command: bin/worker
    env: {}
    image: gilliam/scheduler:f3f3bfb5
    ports: []
  api:
    command: bin/api
    env: {}
    image: gilliam/scheduler:f3f3bfb5
    ports:
    - 80
