author: jrydberg
kind: gilliam#release
message: null
name: '2'
services:
  _bootstrap:
    command: bin/bootstrap
    env: {}
    image: gilliam/scheduler:e4a94d4d
    ports: []
  _store:
    command: null
    env: {}
    image: gilliam/etcd
    ports:
    - 4001
    - 7001
  _worker:
    command: bin/worker
    env: {}
    image: gilliam/scheduler:e4a94d4d
    ports: []
  api:
    command: bin/api
    env: {}
    image: gilliam/scheduler:e4a94d4d
    ports:
    - 80
